parameters:     
    nzo_url_encryptor.class:    Nzo\UrlEncryptorBundle\UrlEncryptor\UrlEncryptor

services:
    nzo_url_encryptor:
        class:    "%nzo_url_encryptor.class%"
        arguments: [%nzo_url_encryptor.secret_key%]

    nzo.twig.url_encryptor_extension:
        class: Nzo\UrlEncryptorBundle\Twig\UrlEncryptorExtension
        arguments: ["@nzo_url_encryptor"]
        tags:
          - { name: twig.extension }