language: php

php:
  - 5.3
  - 5.4
  - 5.5


before_script:
  - composer selfupdate
  - composer --prefer-source install

#script: phpunit --debug

notifications:
  email:
    - alakhefifi@gmail.com
